// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleIMS.Data;

#nullable disable

namespace SimpleIMS.Migrations
{
    [DbContext(typeof(SimpleIMSDbContext))]
    [Migration("20220522103138_ProductAndCategoryDataSeed")]
    partial class ProductAndCategoryDataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimpleIMS.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7336),
                            Name = "Laptops",
                            UpdatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7337)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7341),
                            Name = "Phones",
                            UpdatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7341)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7342),
                            Name = "Accessories",
                            UpdatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7343)
                        });
                });

            modelBuilder.Entity("SimpleIMS.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7366),
                            Description = "Asus VivoBook S14 is a Windows 10 Home laptop with a 14.00-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i5 processor and it comes with 8GB of RAM. The Asus VivoBook S14 packs 128GB of SSD storage. Graphics are powered by Intel Integrated UHD Graphics 620. Connectivity options include Wi-Fi 802.11 ac, Bluetooth and it comes with 4 USB ports (2 x USB 2.0, 1 x USB 3.0), Mic In ports.",
                            Name = "ASUS VivoBook S14",
                            Price = 215000m,
                            Quantity = 5,
                            UpdatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7366)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7371),
                            Description = "The most powerful MacBook Pro ever is here. With the blazing-fast M1 Pro or M1 Max chip — the first Apple silicon designed for pros — you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need. The first notebook of its kind, this MacBook Pro is a beast.",
                            Name = "MacBook Pro 16-inch",
                            Price = 1475000m,
                            Quantity = 3,
                            UpdatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7371)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7372),
                            Description = "Powered by an Intel® Core™ processor, the Victus by HP 16.1 inch laptop has all the features to handle your gaming and daily needs. Increase your gaming flexibility with an all-purpose gaming keyboard and enjoy a tear-free fast refresh rate display. Power through the heat of every game with a cooling system that prevents overheating. Elevate your gaming experience beyond your hardware with the OMEN Gaming Hub.",
                            Name = "HP Victus 16-e0043ur",
                            Price = 426000m,
                            Quantity = 10,
                            UpdatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7373)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7374),
                            Description = "Apple's iPhone 13 features a ceramic shield front, Super Retina XDR display with True Tone and an A15 Bionic chip. The first design change users will notice is the smaller notch. After years of using the same-sized notch to house the Face ID components, Apple has finally reduced its size by 20%.",
                            Name = "iPhone 13",
                            Price = 480000m,
                            Quantity = 25,
                            UpdatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7374)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7375),
                            Description = "The Samsung Galaxy S21 is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Name = "Samsung Galaxy S21",
                            Price = 300000m,
                            Quantity = 25,
                            UpdatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7375)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7378),
                            Description = "Xiaomi Mi 11 smartphone comes with a transparent silicone case, adapter from Type-C to 3.5 mm audio jack, power adapter and charging cable.",
                            Name = "Xiaomi Mi 11",
                            Price = 170000m,
                            Quantity = 40,
                            UpdatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7378)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7379),
                            Description = "The AirPods Pro are the more premium version of Apple's standard AirPods. They feature two audio modes for filtering outside sounds, changeable ear tips, and the H1 processor. Gyroscopes in the earpieces enable users to move their head 'around' within an audio space using a feature called Spatial Audio.",
                            Name = "AirPods Pro",
                            Price = 95000m,
                            Quantity = 30,
                            UpdatedAt = new DateTime(2022, 5, 22, 10, 31, 37, 769, DateTimeKind.Utc).AddTicks(7380)
                        });
                });

            modelBuilder.Entity("SimpleIMS.Data.Entities.Product", b =>
                {
                    b.HasOne("SimpleIMS.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SimpleIMS.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
